package reporter

import (
	"bufio"
	"go/parser"
	"go/token"
	"os"
	"regexp"
	"strings"
	"unicode"

	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/pkg/errors"
)

func ParseIgnoreFile(filename string) (parsed []*regexp.Regexp, err error) {
	if filename == "" {
		return nil, nil
	}

	file, err := os.Open(filename)
	if err != nil {
		if !errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}

		return nil, errors.WithStack(err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()

		trimmed := strings.TrimLeftFunc(line, unicode.IsSpace)
		if len(trimmed) == 0 || strings.HasPrefix(trimmed, "#") {
			continue
		}

		re, err := regexp.Compile(line)
		if err != nil {
			return parsed, errors.Wrapf(err, "parsing regexp %q", line)
		}

		parsed = append(parsed, re)
	}

	err = scanner.Err()
	if err != nil {
		return parsed, errors.WithStack(err)
	}

	return parsed, nil
}

func IsGenerated(firstLine string) bool {
	firstLine = strings.ToLower(firstLine)
	return strings.Contains(firstLine, "code generated by") && strings.Contains(firstLine, "do not edit")
}

func ShouldSkip(commit *object.Commit, filename string, skipGenerated, skipMain bool) (bool, error) {
	if !skipGenerated && !skipMain {
		return false, nil
	}

	file, err := commit.File(filename)
	if err != nil {
		if errors.Is(err, object.ErrFileNotFound) {
			return false, nil
		}
		return false, errors.WithStack(err)
	}

	r, err := file.Reader()
	if err != nil {
		return false, errors.WithStack(err)
	}

	defer r.Close()

	f, err := parser.ParseFile(token.NewFileSet(), filename, r, parser.PackageClauseOnly|parser.ParseComments)
	if err != nil {
		return false, errors.WithStack(err)
	}

	if skipGenerated && len(f.Comments) > 0 && f.Comments[0].Pos() == 1 && IsGenerated(f.Comments[0].Text()) {
		return true, nil
	}

	if skipMain && f.Name.Name == "main" {
		return true, nil
	}

	return false, nil
}
